site_name: pypath
site_url: https://pypath.omnipathdb.org
repo_url: https://github.com/saezlab/pypath
repo_name: saezlab/pypath
theme:
  name: material
  favicon: assets/favicon.ico
  icon:
    logo: material/database
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths:
        - .
        options:
          show_source: true
          show_root_heading: true
nav:
- Home: index.md
- Installation: installation.md
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- admonition
- toc:
    permalink: true
extra_css:
- assets/omnipath-theme.css
